### ISSUE TITLE
Sensitive data exposed

### ISSUE THREAD

**Issue by bufgix** [emreozgenc/emreozgenc.github.io#1]
https://github.com/emreozgenc/emreozgenc.github.io/blob/eeff463bd91cf794d0dcb3a7fd08ad0f48f15829/src/firebase/firebaseConfig.js#L5

Seems some firebase sensitive information (apiKey, appId etc..) exposed. 

You may want to change firbase app. And you can use [.env](https://create-react-app.dev/docs/adding-custom-environment-variables/#adding-development-environment-variables-in-env) for senstive data

**Comment by emreozgenc** [comment]
I've have forgotton it completely. Thanks for warning. 😅
